# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 646a0516ccf243d96dbc8ee052ee9290814728663b8d51aa3b44011e4e9d4d4972f4f700f8064421c612bc99df892b99554f250442ccf014d075d3339850c3db

test:
  secret_key_base: 1002d255b09c14b688ab96ff0866b74e00e0c6d3403123a6a4b80992a06a4b772112bebc885dab8d687b8fa1f053ef1a0ab4f34f6a2e9c43f45e9aa766bd772b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
